language: node_js
node_js:
  - "stable"
install:
  - npm install
cache:
  directories:
    - "node_modules"
stages:
    - lint
    - test
    - name: distify
      if: branch = master
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run test
    - stage: distify
      script:
        - npm run build
        - bash ./scripts/distify.sh