language: node_js
node_js:
  - "stable"
install:
  - npm install
cache:
  directories:
    - "node_modules"
states:
    - lint
    - test
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run test:only