language: node_js
node_js:
  - "stable"
install:
  - npm install
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: test
    script:
      - npm run lint
      - npm run test:only