name: Publish to NPM

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Publish to npm
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
        run: |
          npm install
          npm publish
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
